#pragma once
#include <cstring>

// ============================================================
// 7-stage halfband FIR cascade interpolator: 44100 → 5644800 Hz (×128)
//
// Each stage is a halfband ×2 lowpass FIR:
//   even output = 0.5 × x[k - N_ODD]        (center coefficient only)
//   odd  output = Σ ODD[j] × (buf[N_ODD-1-j] + buf[N_ODD+j])
//
// Stopband ≥ 120 dB for all stages (Stage 1: -125.8 dB measured).
// Audio passband 0–20 kHz, images rejected ≥ 120 dB.
//
// Coefficients generated by gen_halfband_coeffs.py (Kaiser window, β=12.27).
// ============================================================

// ---- Stage 1: 44100 → 88200 Hz, N=337, N_ODD=84 ----
static constexpr int   STAGE1_ODD_N = 84;
static constexpr float STAGE1_ODD[] = {
    3.182436346029e-01f, -1.059046302578e-01f, 6.333136652825e-02f, -4.501104316939e-02f,
    3.477583553832e-02f, -2.821654853724e-02f, 2.363751182801e-02f, -2.024755783824e-02f,
    1.762795559775e-02f, -1.553638562882e-02f, 1.382292856834e-02f, -1.238988529817e-02f,
    1.117088298727e-02f, -1.011926699085e-02f, 9.201295825951e-03f, -8.391970138000e-03f,
    7.672378251919e-03f, -7.027951716649e-03f, 6.447286561940e-03f, -5.921327229789e-03f,
    5.442789376699e-03f, -5.005743808747e-03f, 4.605311450623e-03f, -4.237436303486e-03f,
    3.898714135266e-03f, -3.586261627833e-03f, 3.297615315161e-03f, -3.030652747565e-03f,
    2.783530438612e-03f, -2.554634625514e-03f, 2.342541912869e-03f, -2.145987611780e-03f,
    1.963840122970e-03f, -1.795080104922e-03f, 1.638783458129e-03f, -1.494107373099e-03f,
    1.360278852924e-03f, -1.236585245355e-03f, 1.122366414447e-03f, -1.017008255411e-03f,
    9.199373136342e-04f, -8.306163137965e-04f, 7.485404406092e-04f, -6.732342410109e-04f,
    6.042490403929e-04f, -5.411607837646e-04f, 4.835682276897e-04f, -4.310914210339e-04f,
    3.833704226219e-04f, -3.400642122472e-04f, 3.008497584359e-04f, -2.654212122132e-04f,
    2.334892010536e-04f, -2.047802013866e-04f, 1.790359716035e-04f, -1.560130305719e-04f,
    1.354821692974e-04f, -1.172279856412e-04f, 1.010484339646e-04f, -8.675438326477e-05f,
    7.416917883371e-05f, -6.312820373713e-05f, 5.347843749807e-05f, -4.507801030473e-05f,
    3.779575185538e-05f, -3.151073462388e-05f, 2.611181188807e-05f, -2.149715132210e-05f,
    1.757376532176e-05f, -1.425703951878e-05f, 1.147026115364e-05f, -9.144149123976e-06f,
    7.216387614551e-06f, -5.631165251725e-06f, 4.338721715613e-06f, -3.294903693958e-06f,
    2.460731977531e-06f, -1.801981383676e-06f, 1.288775057034e-06f, -8.951945396075e-07f,
    5.989068303410e-07f, -3.808094718166e-07f, 2.246945121601e-07f, -1.169319976410e-07f
};

// ---- Stage 2: 88200 → 176400 Hz, N=61, N_ODD=15 ----
static constexpr int   STAGE2_ODD_N = 15;
static constexpr float STAGE2_ODD[] = {
    3.162375703829e-01f, -1.000331499852e-01f, 5.401371983374e-02f, -3.288010405637e-02f,
    2.059340134090e-02f, -1.277918932700e-02f, 7.689888628188e-03f, -4.416737685942e-03f,
    2.386222209723e-03f, -1.193192862315e-03f, 5.407949258746e-04f, -2.154722482374e-04f,
    7.169067631767e-05f, -1.793485825057e-05f, 2.458655818419e-06f
};

// ---- Stage 3: 176400 → 352800 Hz, N=45, N_ODD=11 ----
static constexpr int   STAGE3_ODD_N = 11;
static constexpr float STAGE3_ODD[] = {
    3.144664257586e-01f, -9.507250396073e-02f, 4.681384798210e-02f, -2.470447578178e-02f,
    1.267174523077e-02f, -6.022826878999e-03f, 2.554233958372e-03f, -9.254318531741e-04f,
    2.681174479998e-04f, -5.450303751499e-05f, 5.222125382934e-06f
};

// ---- Stages 4–6: 352800/705600/1411200 → next, N=37, N_ODD=9 (identical) ----
static constexpr int   STAGE4_ODD_N = 9;
static constexpr float STAGE46_ODD[] = {   // same coefficients for stages 4, 5, 6
    3.125842147612e-01f, -9.002294193189e-02f, 4.010200436020e-02f, -1.805824130575e-02f,
    7.361235653717e-03f, -2.530040653454e-03f, 6.741104258035e-04f, -1.194845607944e-04f,
    8.899094619063e-06f
};

// ---- Stage 7: 2822400 → 5644800 Hz, N=33, N_ODD=8 ----
static constexpr int   STAGE7_ODD_N = 8;
static constexpr float STAGE7_ODD[] = {
    3.110785866991e-01f, -8.614496633950e-02f, 3.536045432838e-02f, -1.394851868193e-02f,
    4.659380334827e-03f, -1.186458752381e-03f, 1.941927625423e-04f, -1.239099189072e-05f
};

// ============================================================
// HBStage<N_ODD>: one channel of one halfband ×2 upsampling stage.
//
// Delay buffer: buf[0] = newest input, buf[2*N_ODD-1] = oldest input.
// After pushing input x[k]:
//   even_out = 0.5 * buf[N_ODD]          = 0.5 * x[k - N_ODD]
//   odd_out  = Σ h[j] * (buf[N_ODD-1-j] + buf[N_ODD+j])
// Both outputs share the same group delay of N_ODD input samples.
// ============================================================
template<int N_ODD>
struct HBStage {
    static constexpr int D = 2 * N_ODD;
    float buf[D] = {};

    void process(float in, const float* h, float& ev, float& od) {
        memmove(buf + 1, buf, (D - 1) * sizeof(float));
        buf[0] = in;

        // Correct unity-gain 2x interpolation:
        // even branch should pass the delayed sample at full scale,
        // odd branch needs x2 because these coeffs represent the nonzero halfband taps.
        ev = buf[N_ODD];

        float s = 0.0f;
        for (int j = 0; j < N_ODD; ++j)
            s += h[j] * (buf[N_ODD - 1 - j] + buf[N_ODD + j]);

        od = 2.0f * s;
    }    

    void reset() { memset(buf, 0, sizeof(buf)); }
};

// ============================================================
// HalfbandInterpolator: stereo 44100 Hz → 5644800 Hz (×128)
//
// Call process() once per 44100 Hz stereo PCM sample.
// Fills outL[128] and outR[128] with the 128 DSD-rate samples.
//
// Latency: ~2.2 ms (dominated by Stage 1's 84-sample delay at 44100 Hz).
// Memory:  ~18 KB for all stage delay lines (both channels).
// ============================================================
struct HalfbandInterpolator {
    // One stateful halfband stage per channel.
    // Each stage processes the full stream produced by the previous stage.

    HBStage<STAGE1_ODD_N> s1L, s1R;
    HBStage<STAGE2_ODD_N> s2L, s2R;
    HBStage<STAGE3_ODD_N> s3L, s3R;
    HBStage<STAGE4_ODD_N> s4L, s4R;
    HBStage<STAGE4_ODD_N> s5L, s5R;
    HBStage<STAGE4_ODD_N> s6L, s6R;
    HBStage<STAGE7_ODD_N> s7L, s7R;


    void reset() {
        s1L.reset(); s1R.reset();
        s2L.reset(); s2R.reset();
        s3L.reset(); s3R.reset();
        s4L.reset(); s4R.reset();
        s5L.reset(); s5R.reset();
        s6L.reset(); s6R.reset();
        s7L.reset(); s7R.reset();
    }

    // Process one 44100 Hz stereo sample; fills out[128] at 5644800 Hz.

        void process(float inL, float inR, float outL[128], float outR[128]) {
        float b1L[2],   b1R[2];
        float b2L[4],   b2R[4];
        float b3L[8],   b3R[8];
        float b4L[16],  b4R[16];
        float b5L[32],  b5R[32];
        float b6L[64],  b6R[64];

        // Stage 1: 1 input -> 2 outputs
        s1L.process(inL, STAGE1_ODD, b1L[0], b1L[1]);
        s1R.process(inR, STAGE1_ODD, b1R[0], b1R[1]);

        // Stage 2: process the full stage-1 stream through ONE stateful filter
        for (int i = 0; i < 2; ++i) {
            s2L.process(b1L[i], STAGE2_ODD, b2L[2*i], b2L[2*i+1]);
            s2R.process(b1R[i], STAGE2_ODD, b2R[2*i], b2R[2*i+1]);
        }

        // Stage 3
        for (int i = 0; i < 4; ++i) {
            s3L.process(b2L[i], STAGE3_ODD, b3L[2*i], b3L[2*i+1]);
            s3R.process(b2R[i], STAGE3_ODD, b3R[2*i], b3R[2*i+1]);
        }

        // Stage 4
        for (int i = 0; i < 8; ++i) {
            s4L.process(b3L[i], STAGE46_ODD, b4L[2*i], b4L[2*i+1]);
            s4R.process(b3R[i], STAGE46_ODD, b4R[2*i], b4R[2*i+1]);
        }

        // Stage 5
        for (int i = 0; i < 16; ++i) {
            s5L.process(b4L[i], STAGE46_ODD, b5L[2*i], b5L[2*i+1]);
            s5R.process(b4R[i], STAGE46_ODD, b5R[2*i], b5R[2*i+1]);
        }

        // Stage 6
        for (int i = 0; i < 32; ++i) {
            s6L.process(b5L[i], STAGE46_ODD, b6L[2*i], b6L[2*i+1]);
            s6R.process(b5R[i], STAGE46_ODD, b6R[2*i], b6R[2*i+1]);
        }

        // Stage 7
        for (int i = 0; i < 64; ++i) {
            s7L.process(b6L[i], STAGE7_ODD, outL[2*i], outL[2*i+1]);
            s7R.process(b6R[i], STAGE7_ODD, outR[2*i], outR[2*i+1]);
        }
    }   
};
